"""added date added to contact messages

Revision ID: 18201c26928d
Revises: 8f7e92f05f57
Create Date: 2025-03-25 12:47:44.119993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18201c26928d'
down_revision = '8f7e92f05f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_ministry_projects')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))

    with op.batch_alter_table('ministry_projects', schema=None) as batch_op:
        batch_op.alter_column('ministry_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ministry_projects', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ministry_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('date_added')

    op.create_table('_alembic_tmp_ministry_projects',
    sa.Column('ministry_id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['ministry_id'], ['ministries.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('ministry_id', 'project_id')
    )
    # ### end Alembic commands ###
