"""added mobile number to contact message model

Revision ID: 46679f4e9efb
Revises: 46a8350b3eeb
Create Date: 2025-02-06 17:07:32.222832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46679f4e9efb'
down_revision = '46a8350b3eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_mobile_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('_mobile_number')

    # ### end Alembic commands ###
