"""added date added to pastor model

Revision ID: 46a8350b3eeb
Revises: b900d59529c2
Create Date: 2025-02-06 13:05:24.711804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a8350b3eeb'
down_revision = 'b900d59529c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pastors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pastors', schema=None) as batch_op:
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###
