"""added images to notice

Revision ID: 798d1132f5e0
Revises: 2edf8de20a0a
Create Date: 2025-02-07 19:29:02.547286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798d1132f5e0'
down_revision = '2edf8de20a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notice_text', sa.String(), nullable=False))
        batch_op.drop_column('description')

    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('notice_text')

    # ### end Alembic commands ###
