"""added email to user

Revision ID: b900d59529c2
Revises: bf00b1f301d4
Create Date: 2025-02-05 16:09:36.186882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b900d59529c2'
down_revision = 'bf00b1f301d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.drop_constraint('uq_username', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_username', ['username'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###
